// <auto-generated />
using System;
using CampaignAnalytics.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampaignAnalytics.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // AspNetRoles
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
                b.ToTable("AspNetRoles", (string)null);
            });

            // AspNetUsers (ApplicationUser)
            modelBuilder.Entity("CampaignAnalytics.API.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<int>("AccessFailedCount").HasColumnType("int");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                b.Property<string>("Department").HasColumnType("nvarchar(max)");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                b.Property<string>("FirstName").HasColumnType("nvarchar(max)");
                b.Property<string>("LastName").HasColumnType("nvarchar(max)");
                b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
                b.ToTable("AspNetUsers", (string)null);
            });

            // Campaigns
            modelBuilder.Entity("CampaignAnalytics.API.Models.Campaign", b =>
            {
                b.Property<int>("CampaignId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignId"));
                b.Property<decimal>("Budget").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedByUserId").IsRequired().HasColumnType("nvarchar(450)");
                b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<DateTime?>("EndDate").HasColumnType("datetime2");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<decimal>("SpentAmount").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("CampaignId");
                b.HasIndex("CreatedByUserId").HasDatabaseName("IX_Campaigns_CreatedByUserId");
                b.HasIndex("StartDate").HasDatabaseName("IX_Campaigns_StartDate");
                b.HasIndex("Status").HasDatabaseName("IX_Campaigns_Status");
                b.ToTable("Campaigns");
            });

            // CampaignEvents
            modelBuilder.Entity("CampaignAnalytics.API.Models.CampaignEvent", b =>
            {
                b.Property<long>("EventId").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));
                b.Property<int>("CampaignId").HasColumnType("int");
                b.Property<string>("EventType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Metadata").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("OccurredAt").HasColumnType("datetime2");
                b.Property<decimal?>("Revenue").HasColumnType("decimal(18,2)");
                b.Property<string>("Source").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.HasKey("EventId");
                b.HasIndex("CampaignId").HasDatabaseName("IX_CampaignEvents_CampaignId");
                b.HasIndex("EventType").HasDatabaseName("IX_CampaignEvents_EventType");
                b.HasIndex("OccurredAt").HasDatabaseName("IX_CampaignEvents_OccurredAt");
                b.ToTable("CampaignEvents");
            });

            // LoyaltyPrograms
            modelBuilder.Entity("CampaignAnalytics.API.Models.LoyaltyProgram", b =>
            {
                b.Property<int>("ProgramId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("ProgramId");
                b.ToTable("LoyaltyPrograms");
            });

            // LoyaltyTiers
            modelBuilder.Entity("CampaignAnalytics.API.Models.LoyaltyTier", b =>
            {
                b.Property<int>("TierId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));
                b.Property<int>("MaxPoints").HasColumnType("int");
                b.Property<int>("MinPoints").HasColumnType("int");
                b.Property<decimal>("MultiplierBonus").HasColumnType("decimal(5,2)");
                b.Property<int>("ProgramId").HasColumnType("int");
                b.Property<string>("TierName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("TierId");
                b.HasIndex("ProgramId").HasDatabaseName("IX_LoyaltyTiers_ProgramId");
                b.ToTable("LoyaltyTiers");
            });

            // LoyaltyTransactions
            modelBuilder.Entity("CampaignAnalytics.API.Models.LoyaltyTransaction", b =>
            {
                b.Property<long>("TransactionId").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));
                b.Property<int>("CampaignId").HasColumnType("int");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("PointsEarned").HasColumnType("int");
                b.Property<int>("PointsRedeemed").HasColumnType("int");
                b.Property<int>("ProgramId").HasColumnType("int");
                b.Property<DateTime>("TransactionDate").HasColumnType("datetime2");
                b.Property<string>("TransactionType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("UserId").IsRequired().HasMaxLength(450).HasColumnType("nvarchar(450)");
                b.HasKey("TransactionId");
                b.HasIndex("CampaignId").HasDatabaseName("IX_LoyaltyTransactions_CampaignId");
                b.HasIndex("TransactionDate").HasDatabaseName("IX_LoyaltyTransactions_TransactionDate");
                b.HasIndex("UserId").HasDatabaseName("IX_LoyaltyTransactions_UserId");
                b.ToTable("LoyaltyTransactions");
            });

            // Keyless report entities
            modelBuilder.Entity("CampaignAnalytics.API.Data.CampaignSummaryReport", b =>
            {
                b.Property<int>("CampaignId").HasColumnType("int");
                b.Property<string>("CampaignName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("ROI").HasColumnType("decimal(18,2)");
                b.Property<decimal>("SpentAmount").HasColumnType("decimal(18,2)");
                b.Property<long>("TotalClicks").HasColumnType("bigint");
                b.Property<long>("TotalConversions").HasColumnType("bigint");
                b.Property<long>("TotalImpressions").HasColumnType("bigint");
                b.Property<decimal>("TotalRevenue").HasColumnType("decimal(18,2)");
                b.HasNoKey();
            });

            modelBuilder.Entity("CampaignAnalytics.API.Data.LoyaltyEngagementReport", b =>
            {
                b.Property<int>("ProgramId").HasColumnType("int");
                b.Property<string>("ProgramName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("RedemptionRate").HasColumnType("decimal(18,2)");
                b.Property<int>("TotalMembers").HasColumnType("int");
                b.Property<long>("TotalPointsEarned").HasColumnType("bigint");
                b.Property<long>("TotalPointsRedeemed").HasColumnType("bigint");
                b.HasNoKey();
            });

            // ── Relationships ───────────────────────────────────────────────

            modelBuilder.Entity("CampaignAnalytics.API.Models.Campaign", b =>
            {
                b.HasOne("CampaignAnalytics.API.Models.ApplicationUser", "CreatedByUser")
                    .WithMany("CreatedCampaigns")
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("CreatedByUser");
            });

            modelBuilder.Entity("CampaignAnalytics.API.Models.CampaignEvent", b =>
            {
                b.HasOne("CampaignAnalytics.API.Models.Campaign", "Campaign")
                    .WithMany("Events")
                    .HasForeignKey("CampaignId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Campaign");
            });

            modelBuilder.Entity("CampaignAnalytics.API.Models.LoyaltyTier", b =>
            {
                b.HasOne("CampaignAnalytics.API.Models.LoyaltyProgram", "Program")
                    .WithMany("Tiers")
                    .HasForeignKey("ProgramId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Program");
            });

            modelBuilder.Entity("CampaignAnalytics.API.Models.LoyaltyTransaction", b =>
            {
                b.HasOne("CampaignAnalytics.API.Models.Campaign", "Campaign")
                    .WithMany("LoyaltyTransactions")
                    .HasForeignKey("CampaignId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CampaignAnalytics.API.Models.LoyaltyProgram", "Program")
                    .WithMany("Transactions")
                    .HasForeignKey("ProgramId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CampaignAnalytics.API.Models.ApplicationUser", "User")
                    .WithMany("LoyaltyTransactions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Campaign");
                b.Navigation("Program");
                b.Navigation("User");
            });

            modelBuilder.Entity("CampaignAnalytics.API.Models.ApplicationUser", b =>
            {
                b.Navigation("CreatedCampaigns");
                b.Navigation("LoyaltyTransactions");
            });

            modelBuilder.Entity("CampaignAnalytics.API.Models.Campaign", b =>
            {
                b.Navigation("Events");
                b.Navigation("LoyaltyTransactions");
            });

            modelBuilder.Entity("CampaignAnalytics.API.Models.LoyaltyProgram", b =>
            {
                b.Navigation("Tiers");
                b.Navigation("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
